import {
  Controller,
  Param,
  Post,
  Get,
  Query,
  Body,
  Patch,
} from '@nestjs/common';
import { Types } from 'mongoose';
import { PayrollExecutionService } from './payroll-execution.service';
import { BonusStatus } from './enums/payroll-execution-enum';
import { employeePayrollDetails } from './models/employeePayrollDetails.schema';
import { payrollRuns } from './models/payrollRuns.schema';

@Controller('payroll-execution')
export class PayrollExecutionController {
  constructor(
    private readonly payrollService: PayrollExecutionService,
  ) {}

  /* =========================
     TASK B – PAYROLL RUNS
     ========================= */

  // ✅ Main table
  @Get('runs')
  async getAllPayrollRuns(): Promise<payrollRuns[]> {
    return this.payrollService.getAllPayrollRuns();
  }

  // ✅ Single payroll run by business runId (PR-2025-0004)
  @Get('runs/:runId')
  async getPayrollRunByRunId(@Param('runId') runId: string) {
    return this.payrollService.getRunByRunId(runId);
  }

  // ✅ Create draft payroll run
  @Post('draft-run')
  async createDraftRun(
    @Query('entity') entity: string,
    @Query('payrollSpecialistId') payrollSpecialistId: string,
    @Query('period') period: string,
  ) {
    const payrollPeriod = new Date(period);

    const draftRun = await this.payrollService.createDraftPayrollRun(
      entity,
      payrollPeriod,
      new Types.ObjectId(payrollSpecialistId),
    );

    return { success: true, draftRun };
  }

  // ✅ Auto-generate draft payroll run (REQ-PY-4)
  @Post('runs/auto-generate')
  async autoGenerateDraftRun(
    @Body('entity') entity: string,
    @Body('payrollSpecialistId') payrollSpecialistId: string,
    @Body('payrollPeriod') payrollPeriod?: string,
  ) {
    const draftRun = await this.payrollService.autoGenerateDraftPayrollRun(
      entity,
      payrollSpecialistId,
      payrollPeriod,
    );

    return { success: true, draftRun };
  }

  // ✅ Auto payroll initiation (REQ-PY-23)
  @Post('runs/auto-initiate')
  async autoInitiatePayroll(
    @Body('entity') entity: string,
    @Body('payrollSpecialistId') payrollSpecialistId: string,
    @Body('payrollPeriod') payrollPeriod?: string,
  ) {
    const run = await this.payrollService.initiatePayrollAutomatically(
      entity,
      payrollSpecialistId,
      payrollPeriod,
    );

    return { success: true, payrollRun: run };
  }

  /* =========================
     PREVIEW & CALCULATION
     ========================= */

  // ✅ PREVIEW (REQ-PY-6)
  @Get('preview/:runId')
  async previewPayroll(@Param('runId') runId: string) {
    const preview =
      await this.payrollService.getPayrollPreview(runId);
    return { success: true, preview };
  }

  // ✅ CALCULATE
  @Post('calculate/:runId')
  async calculatePayroll(@Param('runId') runId: string) {
    const result =
      await this.payrollService.calculatePayrollForRun(runId);

    return { success: true, details: result };
  }

  // ✅ Review & approve initiation (REQ-PY-24)
  @Patch('runs/:runId/initiation/approve')
  async approveInitiation(
    @Param('runId') runId: string,
    @Body('payrollSpecialistId') payrollSpecialistId: string,
  ) {
    const payrollRun =
      await this.payrollService.approvePayrollInitiation(
        runId,
        payrollSpecialistId,
      );

    return { success: true, payrollRun };
  }

  // ✅ Manual edit initiation (REQ-PY-26)
  @Patch('runs/:runId/initiation')
  async editInitiation(
    @Param('runId') runId: string,
    @Body('payrollSpecialistId') payrollSpecialistId: string,
    @Body()
    updates: Partial<{
      entity: string;
      employees: number;
      exceptions: number;
      totalnetpay: number;
    }>,
  ) {
    const payrollRun =
      await this.payrollService.editPayrollInitiation(
        runId,
        payrollSpecialistId,
        updates,
      );

    return { success: true, payrollRun };
  }

  /* =========================
     APPROVAL FLOW
     ========================= */

  @Post('send-for-approval/:runId')
  async sendForApproval(
    @Param('runId') runId: string,
    @Body('managerId') managerId: string,
    @Body('financeId') financeId: string,
  ) {
    const updatedRun =
      await this.payrollService.sendPayrollForApproval(
        runId,
        managerId,
        financeId,
      );

    return { success: true, payrollRun: updatedRun };
  }

  @Patch(':id/approve-by-manager')
  async approveByManager(
    @Param('id') payrollRunId: string,
    @Body('managerId') managerId: string,
  ) {
    return this.payrollService.approvePayrollByManager(
      payrollRunId,
      managerId,
    );
  }

  @Patch(':id/finance-approve')
  async approvePayrollByFinance(
    @Param('id') payrollRunId: string,
    @Body('financeStaffId') financeStaffId: string,
  ) {
    return this.payrollService.approvePayrollByFinance(
      payrollRunId,
      financeStaffId,
    );
  }

  /* =========================
     LOCK / UNLOCK
     ========================= */

  @Post('lock/:runId')
  async lockPayrollRun(
    @Param('runId') runId: string,
    @Body('managerId') managerId: string,
  ) {
    return this.payrollService.lockPayrollRun(runId, managerId);
  }

  @Post('unlock/:runId')
  async unlockPayrollRun(
    @Param('runId') runId: string,
    @Body('managerId') managerId: string,
    @Body('reason') reason: string,
  ) {
    return this.payrollService.unlockPayrollRun(
      runId,
      managerId,
      reason,
    );
  }



  /* =========================
     SIGNING BONUSES
     ========================= */
  
  @Get('signing-bonuses')
  async getAllSigningBonuses() {
    const bonuses = await this.payrollService.getAllSigningBonuses();
    return { success: true, bonuses };
  }

  @Post('signing-bonus/approve/:bonusId')
  async approveSigningBonus(
    @Param('bonusId') bonusId: string,
    @Query('payrollRunId') payrollRunId: string,
  ) {
    const approvedBonus =
      await this.payrollService.approveEmployeeSigningBonus(
        bonusId,
        payrollRunId,
      );

    return { success: true, bonus: approvedBonus };
  }

  @Patch('signing-bonus/edit/:id')
  async editSigningBonus(
    @Param('id') id: string,
    @Body() body: { paymentDate?: string; status?: BonusStatus },
  ) {
    const updatedBonus =
      await this.payrollService.editEmployeeSigningBonus(
        id,
        {
          paymentDate: body.paymentDate
            ? new Date(body.paymentDate)
            : undefined,
          status: body.status,
        },
      );

    return { success: true, updatedBonus };
  }

  /* =========================
     RESIGNATION & TERMINATION BENEFITS
     ========================= */

  @Get('resignation-benefits')
  async getResignationBenefits() {
    const benefits = await this.payrollService.getResignationBenefits();
    return { success: true, benefits };
  }

  @Get('termination-benefits')
  async getTerminationBenefits() {
    const benefits = await this.payrollService.getTerminationBenefits();
    return { success: true, benefits };
  }

  @Post('resignation-benefits/:employeeId/:payrollRunId')
  async processResignationBenefits(
    @Param('employeeId') employeeId: string,
    @Param('payrollRunId') payrollRunId: string,
  ) {
    const result =
      await this.payrollService.processResignationBenefits(
        employeeId,
        payrollRunId,
      );

    return { success: true, payrollDetails: result };
  }

  @Post('resignation-benefits/approve/:employeePayrollDetailId')
  async approveResignationBenefits(
    @Param('employeePayrollDetailId') employeePayrollDetailId: string,
  ): Promise<{ success: boolean; payrollDetail: employeePayrollDetails }> {
    const payrollDetail =
      await this.payrollService.approveResignationBenefits(
        new Types.ObjectId(employeePayrollDetailId),
      );

    return { success: true, payrollDetail };
  }

  /* =========================
     PAYSLIPS (REQ-PY-8)
     ========================= */
  @Get('runs/:runId/payslips')
  async getPayslipsForRun(@Param('runId') runId: string) {
    const payslips = await this.payrollService.getPayslipsForRun(runId);
    return { success: true, payslips };
  }

  /* =========================
     IRREGULARITIES RESOLUTION
     ========================= */
  
  // Get irregularities for a specific run
  @Get('runs/:runId/irregularities')
  async getIrregularitiesByRun(@Param('runId') runId: string) {
    const preview = await this.payrollService.getPayrollPreview(runId);
    return { success: true, irregularities: preview.irregularities || [] };
  }

  // Get all irregularities across all runs
  @Get('irregularities')
  async getAllIrregularities() {
    const allIrregularities = await this.payrollService.getAllIrregularities();
    return { success: true, irregularities: allIrregularities };
  }

  @Post('runs/:runId/resolve-irregularities')
  async resolveIrregularities(
    @Param('runId') runId: string,
    @Body('managerId') managerId: string,
    @Body('resolvedDetails')
    resolvedDetails: { employeeId: string; resolutionNote: string }[] = [],
  ) {
    const payrollRun = await this.payrollService.resolvePayrollIrregularity(
      runId,
      managerId,
      resolvedDetails,
    );
    return { success: true, payrollRun };
  }
}
