import api from '@/lib/axios';
import { PayrollPreview, PayrollRun } from '@/types/payroll-run.types';

interface RunInitPayload {
  entity: string;
  payrollSpecialistId: string;
  payrollPeriod?: string;
}

export const payrollRunService = {
  // 📌 Main table
  getAllPayrollRuns: async (): Promise<PayrollRun[]> => {
    const response = await api.get('/payroll-execution/runs');
    return response.data;
  },

  // 📌 Single payroll run (by business runId)
  getPayrollRunByRunId: async (runId: string): Promise<PayrollRun> => {
    const response = await api.get(
      `/payroll-execution/runs/${runId}`
    );
    return response.data;
  },

  getPayrollPreview: async (runId: string): Promise<PayrollPreview> => {
    const response = await api.get(
      `/payroll-execution/preview/${runId}`
    );
    return response.data.preview;
  },

  sendForApproval: async (
    runId: string,
    managerId: string,
    financeId: string,
  ): Promise<PayrollRun> => {
    const response = await api.post(
      `/payroll-execution/send-for-approval/${runId}`,
      { managerId, financeId }
    );
    return response.data.payrollRun;
  },

  autoGenerateDraftRun: async (
    payload: RunInitPayload,
  ): Promise<PayrollRun> => {
    const response = await api.post(
      '/payroll-execution/runs/auto-generate',
      payload,
    );
    return response.data.draftRun;
  },

  autoInitiateRun: async (
    payload: RunInitPayload,
  ): Promise<PayrollRun> => {
    const response = await api.post(
      '/payroll-execution/runs/auto-initiate',
      payload,
    );
    return response.data.payrollRun;
  },

  approveInitiation: async (
    runId: string,
    payrollSpecialistId: string,
  ): Promise<PayrollRun> => {
    const response = await api.patch(
      `/payroll-execution/runs/${runId}/initiation/approve`,
      { payrollSpecialistId },
    );
    return response.data.payrollRun;
  },

  editInitiation: async (
    runId: string,
    payrollSpecialistId: string,
    updates: Partial<{
      entity: string;
      employees: number;
      exceptions: number;
      totalnetpay: number;
    }>,
  ): Promise<PayrollRun> => {
    const response = await api.patch(
      `/payroll-execution/runs/${runId}/initiation`,
      {
        payrollSpecialistId,
        ...updates,
      },
    );
    return response.data.payrollRun;
  },

  // Manager approval
  approveByManager: async (runId: string, managerId: string): Promise<PayrollRun> => {
    const res = await api.patch(`/payroll-execution/${runId}/approve-by-manager`, { managerId });
    return res.data;
  },

  // Finance approval
  approveByFinance: async (runId: string, financeStaffId: string): Promise<PayrollRun> => {
    const res = await api.patch(`/payroll-execution/${runId}/finance-approve`, { financeStaffId });
    return res.data;
  },

  // Lock / Unlock
  lockRun: async (runId: string, managerId: string): Promise<PayrollRun> => {
    const res = await api.post(`/payroll-execution/lock/${runId}`, { managerId });
    return res.data;
  },
  unlockRun: async (runId: string, managerId: string, reason: string): Promise<PayrollRun> => {
    const res = await api.post(`/payroll-execution/unlock/${runId}`, { managerId, reason });
    return res.data;
  },

  // Resolve irregularities
  resolveIrregularities: async (
    runId: string,
    managerId: string,
    resolvedDetails: { employeeId: string; resolutionNote: string }[],
  ): Promise<PayrollRun> => {
    const res = await api.post(`/payroll-execution/runs/${runId}/resolve-irregularities`, {
      managerId,
      resolvedDetails,
    });
    return res.data.payrollRun;
  },
};
