'use client';

import { useEffect, useState } from 'react';
import { payrollRunService } from '@/services/api/payroll-run.service';
import { PayrollRun } from '@/types/payroll-run.types';
import PayrollRunTable from '@/components/payroll-execution/PayrollRunTable';

export default function PayrollExecutionPage() {
  const [runs, setRuns] = useState<PayrollRun[]>([]);
  const [loading, setLoading] = useState(true);
  const [form, setForm] = useState({
    entity: '',
    payrollSpecialistId: '',
    payrollPeriod: '',
  });
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const isValidObjectId = (id: string) => /^[a-fA-F0-9]{24}$/.test(id?.trim() ?? '');

  const fetchRuns = async () => {
    try {
      const data = await payrollRunService.getAllPayrollRuns();
      setRuns(data);
    } catch (err) {
      console.error('Error fetching payroll runs:', err);
      setMessage('Unable to load payroll runs.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRuns();
  }, []);

  const handleGenerateDraft = async () => {
    setMessage(null);
    setError(null);

    if (!isValidObjectId(form.payrollSpecialistId)) {
      setError('Enter a valid 24-char payrollSpecialistId (Mongo ObjectId)');
      return;
    }
    try {
      await payrollRunService.autoGenerateDraftRun(form);
      await fetchRuns();
      setMessage('Draft payroll run generated.');
    } catch (err) {
      console.error(err);
      setMessage('Could not auto-generate draft run.');
    }
  };

  const handleAutoInitiate = async () => {
    setMessage(null);
    setError(null);

    if (!isValidObjectId(form.payrollSpecialistId)) {
      setError('Enter a valid 24-char payrollSpecialistId (Mongo ObjectId)');
      return;
    }
    try {
      await payrollRunService.autoInitiateRun(form);
      await fetchRuns();
      setMessage('Payroll initiation processed.');
    } catch (err) {
      console.error(err);
      setMessage('Could not process payroll initiation.');
    }
  };

  if (loading) return <div>Loading payroll runs...</div>;
  if (!runs.length)
    return (
      <div className="p-6 space-y-4">
        <RunActions
          form={form}
          setForm={setForm}
          onGenerate={handleGenerateDraft}
          onInitiate={handleAutoInitiate}
          message={message}
          error={error}
        />
        <div>No payroll runs found.</div>
      </div>
    );

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Payroll Runs</h1>
      </div>

      <RunActions
        form={form}
        setForm={setForm}
        onGenerate={handleGenerateDraft}
        onInitiate={handleAutoInitiate}
        message={message}
        error={error}
      />

      <PayrollRunTable runs={runs} />
    </div>
  );
}

function RunActions({
  form,
  setForm,
  onGenerate,
  onInitiate,
  message,
  error,
}: {
  form: { entity: string; payrollSpecialistId: string; payrollPeriod: string };
  setForm: React.Dispatch<React.SetStateAction<{ entity: string; payrollSpecialistId: string; payrollPeriod: string }>>;
  onGenerate: () => void;
  onInitiate: () => void;
  message: string | null;
  error: string | null;
}) {
  return (
    <div className="glass-card space-y-3 p-4">
      <div className="flex flex-wrap gap-3">
        <input
          placeholder="Entity"
          value={form.entity}
          onChange={(e) => setForm((prev) => ({ ...prev, entity: e.target.value }))}
          className="min-w-[200px] rounded-lg border border-white/10 bg-white/5 p-2 text-sm"
        />
        <input
          placeholder="Payroll Specialist ID"
          value={form.payrollSpecialistId}
          onChange={(e) => setForm((prev) => ({ ...prev, payrollSpecialistId: e.target.value }))}
          className="min-w-[220px] rounded-lg border border-white/10 bg-white/5 p-2 text-sm"
        />
        <input
          placeholder="Payroll Period (optional, ISO date)"
          value={form.payrollPeriod}
          onChange={(e) => setForm((prev) => ({ ...prev, payrollPeriod: e.target.value }))}
          className="min-w-[240px] rounded-lg border border-white/10 bg-white/5 p-2 text-sm"
        />
        <button
          onClick={onGenerate}
          className="rounded-lg bg-cyan-500 px-4 py-2 text-sm font-semibold text-slate-900 hover:bg-cyan-400"
        >
          Auto-generate draft
        </button>
        <button
          onClick={onInitiate}
          className="rounded-lg border border-white/10 bg-white/5 px-4 py-2 text-sm text-slate-100 hover:bg-white/10"
        >
          Auto payroll initiation
        </button>
      </div>
      {error && <div className="text-sm text-rose-300">{error}</div>}
      {message && <div className="text-sm text-slate-200">{message}</div>}
    </div>
  );
}
